#product
debug = true

# period second
period = 120

# NSQ  crawling  queue
crawler_addr = "10.8.15.9:4161"
crawler_topic = "topic_crawling"
crawler_channel = "chan_doing"

# NSQ  storaging  queue
storage_addr = "10.8.15.9:4161"
storage_topic = "topic_storage"
storage_channel = "doing"


#product
debug = true

# Nsq queue
nsq_addr = "10.8.15.9:4161"
nsq_topic = "topic_passive"
nsq_channel = "chan_doing"


# ES search engine
#es_addr = "http://10.8.15.168:9200"
#es_index = "passive"
#es_type = "product"
